version: "3"

services:
  nextjs:
    build: ./nextjs
    container_name: nextjs
    restart: always
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5000:3000/tcp
      - 3443:443/tcp
      - 3443:443/udp
      - 853:853/tcp
      - 853:853/udp
    volumes:
      - ./adguard/conf/:/opt/adguardhome/conf/:rw
      - ./adguard/work/:/opt/adguardhome/work/:rw
      - ./letsencrypt/certs/:/certs/:ro
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    # uncomment after ssl certificate is generated
    # command: '--sslcert /certs/live/corliansa.xyz/fullchain.pem --sslkey /certs/live/corliansa.xyz/privkey.pem'
    ports:
      - 9443:9443
    volumes:
      - ./portainer/data/:/data/:rw
      - /var/run/docker.sock/:/var/run/docker.sock/:rw
      - ./letsencrypt/certs/:/certs/:ro
  coolify:
    image: coollabsio/coolify:latest
    restart: always
    container_name: coolify
    ports:
      - 3000:3000
    volumes:
      - ./coolify/backups/:/app/backups/:rw
      - ./coolify/db/:/app/db/:rw
      - ./coolify/logs/:/app/logs/:rw
      - ./coolify/ssl/:/app/ssl/:rw
      - ./letsencrypt/acme/:/etc/traefik/acme/:rw
      - ./letsencrypt/certs/:/etc/letsencrypt/:rw
      - /var/run/docker.sock/:/var/run/docker.sock/:rw
    environment:
      - COOLIFY_APP_ID
      - COOLIFY_SECRET_KEY
      - COOLIFY_DATABASE_URL=file:../db/prod.db
      - COOLIFY_IS_ON=docker
      - COOLIFY_WHITE_LABELED=false
      - COOLIFY_WHITE_LABELED_ICON=
      - COOLIFY_AUTO_UPDATE=false
  fluent-bit:
    image: coollabsio/coolify-fluent-bit:1.0.0
    container_name: coolify-fluentbit
    volumes:
      - ./coolify/logs/:/app/logs/:rw
  replacer:
    image: corliansa/ext-replacer:latest
    depends_on:
      - coolify
    container_name: replacer
    restart: always
    volumes:
      - ./replacer/data/:/usr/app/data/:rw
    environment:
      - HTTP_PATH=http://coolify:3000/webhooks/traefik/main.json
      - JSON_PATH=/usr/app/data/data.js
  traefik:
    image: traefik:latest
    depends_on:
      - replacer
    container_name: traefik
    restart: always
    volumes:
      - ./letsencrypt/acme/:/etc/traefik/acme/:rw
      - /var/run/docker.sock/:/var/run/docker.sock/:rw
    command: "--accesslog=true --entrypoints.web.address=:80 --entrypoints.web.forwardedHeaders.insecure=true --entrypoints.websecure.address=:443 --entrypoints.websecure.forwardedHeaders.insecure=true --providers.docker=true --providers.docker.exposedbydefault=false --providers.http.endpoint=http://coolify:3000/webhooks/traefik/main.json --providers.http.pollTimeout=5s --certificatesresolvers.letsencrypt.acme.httpchallenge=true --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web --log.level=error"
    networks:
      - default
      - coolify

networks:
  default:
  coolify:
    external: true
    name: coolify
